name: OCaml

on:
  - pull_request
  - push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        ocaml-version:
          - 4.12.0
          - 4.11.2
          - 4.10.1

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - run: opam depext anders --yes
      - run: opam install . --deps-only
      - run: opam exec -- dune build
      - run: opam install .
      - run: dune exec anders check lib/mltt.anders
      - run: dune exec anders check lib/buddhism.anders
      - run: dune exec anders check lib/cat.anders
      - run: dune exec anders check lib/church.anders
      - run: dune exec anders check lib/fun.anders
      - run: dune exec anders check lib/impredicative.anders
      - run: dune exec anders check lib/kraus.anders
      - run: dune exec anders check lib/leibniz.anders
      - run: dune exec anders check lib/list.anders
      - run: dune exec anders check lib/mltt.anders
      - run: dune exec anders check lib/path.anders
      - run: dune exec anders check lib/pi.anders
      - run: dune exec anders check lib/topos.anders
